services:
  app:
    # Option 1: Use pre-built image (update with your actual image)
    # image: ghcr.io/nghyanenghyanenghyane/truyenqq-clone:latest

    # Option 2: Build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - tunnel-network
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run --token ${CLOUDFLARED_TOKEN}
    networks:
      - tunnel-network
    depends_on:
      - app
    restart: unless-stopped

networks:
  tunnel-network:
    driver: bridge
